/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleAgentActivityRouteImport } from './routes/_console.agent-activity'
import { Route as ConsoleAlertsRouteImport } from './routes/_console.alerts'
import { Route as ConsoleAssistantRouteImport } from './routes/_console.assistant'
import { Route as ConsoleDashboardRouteImport } from './routes/_console.dashboard'
import { Route as ConsoleInventoryRouteImport } from './routes/_console.inventory'
import { Route as ConsoleReportsRouteImport } from './routes/_console.reports'
import { Route as ConsoleSettingsRouteImport } from './routes/_console.settings'
import { Route as ConsoleShelvesRouteImport } from './routes/_console.shelves'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAgentActivityRoute = ConsoleAgentActivityRouteImport.update({
  id: '/agent-activity',
  path: '/agent-activity',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAlertsRoute = ConsoleAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAssistantRoute = ConsoleAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleInventoryRoute = ConsoleInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleReportsRoute = ConsoleReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleShelvesRoute = ConsoleShelvesRouteImport.update({
  id: '/shelves',
  path: '/shelves',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-activity': typeof ConsoleAgentActivityRoute
  '/alerts': typeof ConsoleAlertsRoute
  '/assistant': typeof ConsoleAssistantRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/inventory': typeof ConsoleInventoryRoute
  '/reports': typeof ConsoleReportsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/shelves': typeof ConsoleShelvesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-activity': typeof ConsoleAgentActivityRoute
  '/alerts': typeof ConsoleAlertsRoute
  '/assistant': typeof ConsoleAssistantRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/inventory': typeof ConsoleInventoryRoute
  '/reports': typeof ConsoleReportsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/shelves': typeof ConsoleShelvesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/_console/agent-activity': typeof ConsoleAgentActivityRoute
  '/_console/alerts': typeof ConsoleAlertsRoute
  '/_console/assistant': typeof ConsoleAssistantRoute
  '/_console/dashboard': typeof ConsoleDashboardRoute
  '/_console/inventory': typeof ConsoleInventoryRoute
  '/_console/reports': typeof ConsoleReportsRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/shelves': typeof ConsoleShelvesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-activity'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/shelves'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-activity'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/inventory'
    | '/reports'
    | '/settings'
    | '/shelves'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/_console/agent-activity'
    | '/_console/alerts'
    | '/_console/assistant'
    | '/_console/dashboard'
    | '/_console/inventory'
    | '/_console/reports'
    | '/_console/settings'
    | '/_console/shelves'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/agent-activity': {
      id: '/_console/agent-activity'
      path: '/agent-activity'
      fullPath: '/agent-activity'
      preLoaderRoute: typeof ConsoleAgentActivityRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/alerts': {
      id: '/_console/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof ConsoleAlertsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/assistant': {
      id: '/_console/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof ConsoleAssistantRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/dashboard': {
      id: '/_console/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/inventory': {
      id: '/_console/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ConsoleInventoryRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/reports': {
      id: '/_console/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ConsoleReportsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/shelves': {
      id: '/_console/shelves'
      path: '/shelves'
      fullPath: '/shelves'
      preLoaderRoute: typeof ConsoleShelvesRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAgentActivityRoute: typeof ConsoleAgentActivityRoute
  ConsoleAlertsRoute: typeof ConsoleAlertsRoute
  ConsoleAssistantRoute: typeof ConsoleAssistantRoute
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleInventoryRoute: typeof ConsoleInventoryRoute
  ConsoleReportsRoute: typeof ConsoleReportsRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleShelvesRoute: typeof ConsoleShelvesRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAgentActivityRoute: ConsoleAgentActivityRoute,
  ConsoleAlertsRoute: ConsoleAlertsRoute,
  ConsoleAssistantRoute: ConsoleAssistantRoute,
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleInventoryRoute: ConsoleInventoryRoute,
  ConsoleReportsRoute: ConsoleReportsRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleShelvesRoute: ConsoleShelvesRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
